---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine

inputs:
- name: frontend

caches:
- path: frontend/node_modules

outputs:
- name: reports

run:
  path: sh
  args:
  - -exc
  - |
    npm install --prefix frontend
    npm run unit --prefix frontend
    pwd
    ls -l frontend/report
