---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine

inputs:
- name: frontend

run:
  path: sh
  args:
  - -exc
  - |
    cd frontend
    npm run test
