---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine

inputs:
- name: frontend

run:
  dir: frontend
  path: sh
  args:
  - -exc
  - |
    npm install
    npm run test
